server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/ecommerce?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: root
    name: E-COMMERCE-DEV-DB
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
app:
  order:
    clientBackUrl: http://localhost:8080/products
    returnUrl: https://7111-220-133-92-216.ngrok-free.app/callback
  security:
    secret-key: 397A24432646294A404E635166546A576E5A7234753778214125442A472D4B61